version: "3.8"
services:
  app:
    build: .
    container_name: nareman
    ports:
      - "4040:3000"
    environment:
      - NODE_ENV=development
   # volumes:
    #  - .:/app
    restart: unless-stopped